# Generated by Django 5.2.7 on 2025-10-28 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_customer', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_expert', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_size', models.FloatField(help_text='Land size in acres')),
                ('soil_type', models.CharField(choices=[('loamy', 'Loamy'), ('clay', 'Clay'), ('sandy', 'Sandy'), ('silt', 'Silt'), ('peat', 'Peat'), ('chalky', 'Chalky')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('fertilizer_type', models.CharField(choices=[('organic', 'Organic'), ('urea', 'Urea'), ('dap', 'DAP'), ('npk', 'NPK'), ('compost', 'Compost')], max_length=20)),
                ('water_access', models.CharField(choices=[('rainfed', 'Rainfed'), ('irrigation', 'Irrigation'), ('mixed', 'Mixed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('suitability_score', models.FloatField(help_text='Suitability score from 0 to 1')),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='main.farmdata')),
            ],
            options={
                'ordering': ['-suitability_score'],
            },
        ),
    ]
