# Generated by Django 5.2.7 on 2025-10-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certificate_of_practice',
            field=models.FileField(blank=True, null=True, upload_to='expert_documents/certificates/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='expert_documents/ids/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes for verification', null=True),
        ),
    ]
